[toolchain]
profile = "minimal"
# use the nightly version of the last stable toolchain, see <https://forge.rust-lang.org/>
channel = "stable"
components = ["rust-src", "llvm-tools", "rustfmt", "clippy"]
targets = ["loongarch64-unknown-none"]
