OUTPUT_ARCH(loongarch)
ENTRY(_start)
BASE_ADDRESS = 0x80400000;
STEP = 0x20000;

SECTIONS
{
    . = BASE_ADDRESS + STEP*4;
    .text : {
        *(.text.entry)
        *(.text .text.*)
    }
    .rodata : {
        *(.rodata .rodata.*)
        *(.srodata .srodata.*)
    }
    .data : {
        *(.data .data.*)
        *(.sdata .sdata.*)
    }
    .bss : {
        start_bss = .;
        *(.bss .bss.*)
        *(.sbss .sbss.*)
        end_bss = .;
    }
    /DISCARD/ : {
        *(.eh_frame)
        *(.debug*)
    }
}
